FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app 

RUN apt-get update \
&& apt-get install -y git \
&& pip install --upgrade pip \
&& pip install --no-cache-dir -r requirements.txt \
&& pip install git+https://github.com/Pathogen-Genomics-Cymru/covate.git

CMD ["covate"]
